# OTBS
binop_separator = "Back"
brace_style = "PreferSameLine"
comment_width = 100
condense_wildcard_suffixes = true
edition = "2021"
error_on_line_overflow = true
fn_args_layout = "Compressed"
fn_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = false
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
imports_indent = "Block"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 120
newline_style = "unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true
